version: '3.4'

services:
  cassandra:
    image: cassandra:3.11.9
    hostname: cassandra
    ports:
      - '9042:9042'
    healthcheck:
      test: ['CMD-SHELL', "nodetool status | grep '^UN' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: redis:6.0.9
    hostname: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD-SHELL', "redis-cli ping | grep '^PONG' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
