export const APP_ENV = 'APP_ENV';
export const APP_NAME = 'APP_NAME';
export const APP_CLUSTER_NAME = 'APP_CLUSTER_NAME';
export const APP_REGION = 'APP_REGION';
export const APP_AVAIL_ENVIRONMENTS = 'APP_AVAIL_ENVIRONMENTS';
export const APP_AVAIL_REGIONS = 'APP_AVAIL_REGIONS';
