export enum ActionTypes {
  FetchEnvironments = 'FetchEnvironments',
  FetchClusters = 'FetchClusters',
  FetchDatacenters = 'FetchDatacenters',
  FetchDataTypes = 'FetchDataTypes',
  FetchUserInfo = 'FetchUserInfo',
  FetchKeyspaces = 'FetchKeyspaces',
  FetchKeyspaceTables = 'FetchKeyspaceTables',
  FetchKeyspaceDataTypes = 'FetchKeyspaceDataTypes',
  FetchTable = 'FetchTable',
  FetchSchema = 'FetchSchema',
  FetchCassandraFeatures = 'FetchCassandraFeatures',
  LoadQueryHistory = 'LoadQueryHistory',
  AddQueryToHistory = 'AddQueryToHistory',
  SetCurrentKeyspace = 'SetCurrentKeyspace',
  SetCurrentCluster = 'SetCurrentCluster',
  FetchClusterInfo = 'FetchClusterInfo',
  SetDatastoreScope = 'SetDatastoreScope',
}
